In [9]:
import pandas as pd 
dataIris=pd.read_csv('iris.csv')
dataIris.head(5)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [12]:
from sklearn.utils import shuffle
dataIris=shuffle(dataIris)
dataIris.head(5)

    sepal.length  sepal.width  petal.length  petal.width     variety
40           5.0          3.5           1.3          0.3      Setosa
32           5.2          4.1           1.5          0.1      Setosa
53           5.5          2.3           4.0          1.3  Versicolor
61           5.9          3.0           4.2          1.5  Versicolor
22           4.6          3.6           1.0          0.2      Setosa

In [13]:
i=int(len(dataIris)*0.66)      #split data into training set and test set
trainingSet=dataIris.head(i).copy()
testSet=dataIris.tail(len(dataIris)-i).copy()

In [14]:
#trainingSet.index=range(len(trainingSet))
trainingSet.head(5)

    sepal.length  sepal.width  petal.length  petal.width     variety
40           5.0          3.5           1.3          0.3      Setosa
32           5.2          4.1           1.5          0.1      Setosa
53           5.5          2.3           4.0          1.3  Versicolor
61           5.9          3.0           4.2          1.5  Versicolor
22           4.6          3.6           1.0          0.2      Setosa

In [15]:
#testSet.index=range(len(testSet))
testSet.head(5)

     sepal.length  sepal.width  petal.length  petal.width     variety
24            4.8          3.4           1.9          0.2      Setosa
50            7.0          3.2           4.7          1.4  Versicolor
66            5.6          3.0           4.5          1.5  Versicolor
102           7.1          3.0           5.9          2.1   Virginica
13            4.3          3.0           1.1          0.1      Setosa

In [16]:
import math
def euclideanDistance(x1,x2,length):
    distance=0
    for i in range(length):
        distance+=(x1[i]-x2[i])**2
    return math.sqrt(distance)

In [17]:
import operator 
def getNeighbors(trainingSet,testInstanceArray,k):
    trainingSet["distance"]=""
    trainingSetArray=trainingSet.values
    length=len(testInstanceArray)-1
    for i in range(len(trainingSet)):
        dist=euclideanDistance(testInstanceArray,trainingSetArray[i],length)
        trainingSet.iloc[i,5]=dist
    trainingSet.sort_values(by="distance",ascending=True,inplace=True)
    neighbors=trainingSet.iloc[:k,:].copy()
    return neighbors

#demo
# testInstanceArray=[6.3, 3.3, 6.0, 2.5, 'Virginica']
# neighbors=getNeighbors(trainingSet,testInstanceArray,5)
# neighbors

In [18]:
def vote(neighbors):
    classVotes={}
    for i in range(len(neighbors)):
        response=neighbors.iloc[i,-2]
        if response in classVotes:
            classVotes[response]+=1
        else:
            classVotes[response]=1
    sortedVotes=sorted(classVotes.items(),key=operator.itemgetter(1),reverse=True)
    return sortedVotes[0][0]
#demo
# print(vote(neighbors))

In [19]:
def getAccuracy(testSet,predictions):
    correct=0
    testSetArray=testSet.values
    for i in range(len(predictions)):
        if(testSetArray[i][-1] == predictions[i]):
            correct+=1
    return (correct/float(len(testSet)))*100
#demo
# predictions=['Versicolor','Versicolor','Versicolor','Versicolor','aaa']
# accuracy=getAccuracy(testSet.iloc[:5,:],predictions)
# print(accuracy)

In [20]:
#run!
print("Test set:" + str(len(testSet)))
print("Training set: "+str(len(trainingSet)))
#print(testSet)
testSetArray=testSet.values
#print(testSetArray)
predictions=[]
for i in range(len(testSet)):
    neighbors=getNeighbors(trainingSet,testSetArray[i],3)
    result=vote(neighbors)
    predictions.append(result)
    print(">Result:"+ str(result)+"  >Testset:"+str(testSet.iloc[i,-1]))
accuracy=getAccuracy(testSet,predictions)
print("Accuracy: "+str(accuracy))

Test set:51
Training set: 99
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Versicolor  >Testset:Versicolor
>Result:Virginica  >Testset:Virginica
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Virginica  >Testset:Virginica
>Result:Virginica  >Testset:Virginica
>Result:Virginica  >Testset:Virginica
>Result:Setosa  >Testset:Setosa
>Result:Setosa  >Testset:Setosa
>Result:Setosa  >Testset:Setosa
>Result:Virginica  >Testset:Virginica
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Versicolor  >Testset:Versicolor
>Result:Setosa  >Testset:Setosa
>Result:Virginica  >Testset:Virginica
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Versicolor  >Testset:Versicolor
>Result:Versicolor  >Testset:Versicolor
>Result:Virginica  >Testset:Virginica
>Result:Versicolor  >Testset:Versicolor
>Result:Versicolor  >Testset:Versicolor
>Result:Setosa  >Testset:Setosa
>Result:Virginica  >Testset:Virginica
>Result:Setosa  >Testset:Setosa
>Result:Setosa  >Testset:Setosa
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Virginica  >Testset:Virginica
>Result:Setosa  >Testset:Setosa
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Virginica  >Testset:Virginica
>Result:Setosa  >Testset:Setosa
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Versicolor  >Testset:Versicolor
>Result:Setosa  >Testset:Setosa
>Result:Setosa  >Testset:Setosa
>Result:Setosa  >Testset:Setosa
>Result:Versicolor  >Testset:Versicolor
>Result:Virginica  >Testset:Virginica
>Result:Versicolor  >Testset:Versicolor
>Result:Virginica  >Testset:Virginica
>Result:Virginica  >Testset:Virginica
>Result:Setosa  >Testset:Setosa
Accuracy: 100.0